# Generated by Django 5.2.10 on 2026-01-11 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto (Buscando gente)'), ('LLENO', 'Lleno (Listo para pagar)'), ('PAGADO', 'Pagado (Confirmado)'), ('FINALIZADO', 'Finalizado (Servicio prestado)')], default='ABIERTO', max_length=15)),
                ('meta_personas', models.PositiveIntegerField(help_text='Cuántos faltan para cerrar el grupo')),
                ('precio_total_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_comision_lider', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_pools', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='partners.service')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('codigo_qr', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('validado_el', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='pools.pool')),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
