# Generated by Django 5.2.10 on 2026-02-22 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pool',
            options={'verbose_name': 'Pool (Grupo)', 'verbose_name_plural': 'Pools (Grupos)'},
        ),
        migrations.AlterField(
            model_name='pool',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto (Buscando gente)'), ('LLENO', 'Lleno (Listo para pagar)'), ('PAGADO', 'Pagado (Confirmado)'), ('FINALIZADO', 'Finalizado (Servicio prestado)')], default='ABIERTO', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_pools', to=settings.AUTH_USER_MODEL, verbose_name='Líder del Grupo'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='meta_personas',
            field=models.PositiveIntegerField(help_text='Cuántos faltan para cerrar el grupo', verbose_name='Meta de Personas'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='monto_comision_lider',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comisión para el Líder'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='precio_total_servicio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='services.service', verbose_name='Servicio'),
        ),
    ]
