server {
    listen 80;
    server_name 129.213.12.26 palenquego.com www.palenquego.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /home/ubuntu/palenque_flow/staticfiles/;
    }

    location /media/ {
        root /home/ubuntu/palenque_flow;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/palenque_flow/palenque_flow.sock;
    }
}
