# Generated by Django 5.2.10 on 2026-02-22 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='serviceextra',
            name='servicio',
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
        migrations.AlterField(
            model_name='store',
            name='aliado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='Aliado'),
        ),
        migrations.AlterField(
            model_name='store',
            name='biografia',
            field=models.TextField(help_text='Historia y alma del negocio', verbose_name='Historia/Bio'),
        ),
        migrations.AlterField(
            model_name='store',
            name='comision_pactada',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Comisión Pactada (%)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='eslogan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Eslogan'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Logo de la Tienda'),
        ),
        migrations.AlterField(
            model_name='store',
            name='nombre_comercial',
            field=models.CharField(max_length=200, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='store',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='stores/covers/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='store',
            name='ubicacion_gps',
            field=models.CharField(help_text='Lat, Lng', max_length=100, verbose_name='Ubicación GPS'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
