# Generated by Django 5.2.10 on 2026-02-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_linktemplate_servicio'),
        ('partners', '0002_remove_service_categoria_remove_service_tienda_and_more'),
        ('pools', '0002_alter_pool_options_alter_pool_creado_el_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceExtra',
        ),
    ]
