# Generated by Django 5.2.10 on 2026-06-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico para notificaciones', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Formato internacional: +503...', max_length=20, null=True),
        ),
    ]
