"""
Django settings for palenque_flow project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ou3vzf&@-u3oro#@58n(bm(*z3-#rdbnz4yy4d66a5w2tf+$26'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '129.213.12.26', 'localhost', '127.0.0.1', 'palenquego.com', 'www.palenquego.com']


# Application definition

INSTALLED_APPS = [
    'unfold',  # Interfaz moderna para el Admin
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'accounts',
    'partners',
    'transport',
    'pools',
    'marketing',
    'services',
    'safeflow',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Configura el motor de autenticación
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# (Opcional) Configura cuánto tiempo dura la sesión
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # El token dura un día
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # La sesión se puede renovar por una semana
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'palenque_flow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'palenque_flow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if os.environ.get('POSTGRES_DB'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'palenque_db'),
        'USER': os.environ.get('POSTGRES_USER', 'palenque_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'PalenqueFlow2026!'),
        'HOST': 'localhost',
        'PORT': '5432',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-sv' # Español de El Salvador

TIME_ZONE = 'America/El_Salvador'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

import os
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')

# Configuración de correos
if os.environ.get('BREVO_SMTP_PASSWORD'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp-relay.brevo.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'b1c29c001@smtp-brevo.com'
    EMAIL_HOST_PASSWORD = os.environ.get('BREVO_SMTP_PASSWORD')
    DEFAULT_FROM_EMAIL = 'PalenqueGo <lanzadera@palenquego.com>'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'PalenqueGo <lanzadera@palenquego.com>'

TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '8724436963:AAGg1hRarw_hfYNRDD5p5tOsyJ4X6th6zvc')

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Permitir que Django confíe en estas URLs para el envío de formularios/POST
CSRF_TRUSTED_ORIGINS = [
    "http://129.213.12.26",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://palenquego.com",
    "https://palenquego.com",
    "http://www.palenquego.com",
    "https://www.palenquego.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://209.97.146.210",          # Tu IP de DigitalOcean
    "https://palenquegov6.netlify.app"  # Tu frontend en Netlify
]

UNFOLD = {
    "SITE_TITLE": "Palenque Admin",
    "SITE_HEADER": "Palenque Flow",
    "COLORS": {
        "primary": {
            "50": "236 253 245",   # Verde muy claro
            "100": "209 250 229",
            "200": "167 243 208",
            "300": "110 231 183",
            "400": "52 211 153",
            "500": "16 185 129",   # Color principal (el del botón "Iniciar sesión")
            "600": "5 150 105",
            "700": "4 120 87",
            "800": "6 95 70",
            "900": "6 78 59",
            "950": "2 44 34",
        },
    },
}

# Asegúrate de que esto esté así para que las cookies viajen entre dominios
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'



