# Generated by Django 5.2.10 on 2026-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceimage_userswipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='chatbot_script',
            field=models.TextField(blank=True, help_text='Script JS del chatbot de ventas para este servicio', null=True),
        ),
    ]
