# Generated by Django 5.2.10 on 2026-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='comision_plataforma',
            field=models.PositiveIntegerField(default=15, verbose_name='Comisión Plataforma (%)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limite_productos',
            field=models.IntegerField(default=5, verbose_name='Límite de Productos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='permite_rutas',
            field=models.BooleanField(default=False, verbose_name='Permite Crear Rutas'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mensual'),
        ),
    ]
