# Generated by Django 5.2.10 on 2026-02-22 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterField(
            model_name='route',
            name='color_hex',
            field=models.CharField(default='#FF5733', max_length=7, verbose_name='Color Hexadecimal'),
        ),
        migrations.AlterField(
            model_name='route',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='route',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Ruta'),
        ),
        migrations.AlterField(
            model_name='route',
            name='path_svg',
            field=models.TextField(help_text='Coordenadas para dibujo en mapa', verbose_name='Trazo SVG'),
        ),
    ]
