# Generated by Django 5.2.10 on 2026-03-08 16:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('transport', '0002_alter_route_options_alter_route_color_hex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='ruta',
            new_name='route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='route',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='route',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='route',
            name='path_svg',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='placa',
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='included_services',
            field=models.ManyToManyField(blank=True, related_name='included_in_routes', to='services.service'),
        ),
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='Ruta Base', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='price_one_way',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='route',
            name='price_round_trip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='route',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.unit'),
        ),
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='minutes_from_start',
            field=models.IntegerField(default=0, help_text='Minutos estimados desde el punto de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='license_plate',
            field=models.CharField(default='PENDIENTE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default='Unidad Principal', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('ONE_WAY', 'Solo Ida'), ('ROUND_TRIP', 'Ida y Vuelta')], max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
