# Generated by Django 5.2.10 on 2026-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_route_options_alter_stop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='current_lat',
            field=models.FloatField(blank=True, help_text='Latitud actual del GPS', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='current_lng',
            field=models.FloatField(blank=True, help_text='Longitud actual del GPS', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_location_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
